"use client";

import { useState, useEffect } from "react";
import { useIDEStore } from "@/store/ideStore";
import {
  X, Check, FileCode, FileText, Info,
  Settings, Folder, ShieldCheck, Loader2
} from "lucide-react";

interface ReviewModalProps {
  isOpen: boolean;
  onClose: () => void;
  code: string;
  projectId: string;
  language: string;
}

export default function ReviewModal({ isOpen, onClose, code, projectId, language }: ReviewModalProps) {
  const { writeActiveProject } = useIDEStore();
  const [outputDir, setOutputDir] = useState("");
  const [writing, setWriting] = useState(false);
  const [selectedFile, setSelectedFile] = useState<string>("main");
  const [error, setError] = useState<string | null>(null);

  // File Extensions
  const ext = {
    javascript: "js", typescript: "ts", python: "py",
    java: "java", go: "go", rust: "rs", cpp: "cpp",
  }[language.toLowerCase()] || "txt";

  const mainFileName = `index.${ext}`;

  // Generate preview templates matching backend logic
  const packageJsonPreview = JSON.stringify({
    name: projectId.replace("_", "-"),
    version: "1.0.0",
    description: "Generated by CodeSentinel",
    main: mainFileName,
    scripts: {
      start: `node ${mainFileName}`,
      dev: `node --watch ${mainFileName}`
    },
    dependencies: {},
    engines: { node: ">=18" }
  }, null, 2);

  const readmePreview = `# ${projectId}

> Generated by **CodeSentinel** — AI-powered secure code generation pipeline

## Requirement

*(Refer to project request prompt)*

## Pipeline

1. **Developer Agent** — generates code from requirement
2. **E2B Execute** — validates code in sandboxed microVM
3. **Semgrep Scan** — static security analysis
4. **Triage Agent** — filters false positives, assigns score
5. **Synthesizer Agent** — patches real vulnerabilities
6. **Finalize** — saves to long-term memory
`;

  const auditReportPreview = JSON.stringify({
    project_id: projectId,
    language: language,
    security_score: 100,
    findings: [],
    written_at: new Date().toISOString(),
  }, null, 2);

  const files = [
    { id: "main", name: mainFileName, type: "code", label: "Main Code File", content: code },
    ...(language === "javascript" || language === "typescript" ? [
      { id: "package", name: "package.json", type: "config", label: "Node Project Config", content: packageJsonPreview }
    ] : []),
    { id: "readme", name: "README.md", type: "docs", label: "Project Documentation", content: readmePreview },
    { id: "audit", name: ".codesentinel/audit_report.json", type: "audit", label: "Security Audit Report", content: auditReportPreview }
  ];

  const currentFile = files.find(f => f.id === selectedFile) || files[0];

  useEffect(() => {
    if (isOpen) {
      setError(null);
      setWriting(false);
      setSelectedFile("main");
    }
  }, [isOpen]);

  if (!isOpen) return null;

  const handleWrite = async () => {
    setWriting(true);
    setError(null);
    try {
      await writeActiveProject(code);
      onClose();
    } catch (err) {
      setError(err instanceof Error ? err.message : String(err));
    } finally {
      setWriting(false);
    }
  };

  return (
    <div style={{
      position: "fixed", top: 0, left: 0, right: 0, bottom: 0,
      background: "rgba(10, 12, 16, 0.75)",
      backdropFilter: "blur(4px)",
      display: "flex", alignItems: "center", justifyContent: "center",
      zIndex: 9999, padding: 20
    }}>
      <div style={{
        background: "var(--bg-panel)",
        border: "1px solid var(--border-panel)",
        borderRadius: 12,
        width: "90%", maxWidth: 1000,
        height: "80vh",
        display: "flex", flexDirection: "column",
        overflow: "hidden",
        boxShadow: "0 20px 40px rgba(0,0,0,0.5)",
      }}>
        {/* Header */}
        <div style={{
          display: "flex", alignItems: "center", justifyContent: "space-between",
          padding: "16px 20px", borderBottom: "1px solid var(--border-panel)",
          background: "var(--bg-editor)"
        }}>
          <div style={{ display: "flex", alignItems: "center", gap: 10 }}>
            <div style={{
              background: "rgba(122, 162, 247, 0.15)",
              color: "var(--accent-blue)",
              padding: 6, borderRadius: 6, display: "flex"
            }}>
              <ShieldCheck size={18} />
            </div>
            <div>
              <h2 style={{ fontSize: 15, fontWeight: 600, color: "var(--text-bright)", margin: 0 }}>
                Review & Write Code to Disk
              </h2>
              <span style={{ fontSize: 11, color: "var(--text-muted)" }}>
                Verify files before writing to <code>~/CodeSentinel-projects/{projectId}/</code>
              </span>
            </div>
          </div>
          <button
            onClick={onClose}
            style={{
              background: "none", border: "none", cursor: "pointer",
              color: "var(--text-muted)", padding: 4, borderRadius: 4,
              display: "flex", transition: "all 0.15s"
            }}
            onMouseOver={e => e.currentTarget.style.color = "var(--text-bright)"}
            onMouseOut={e => e.currentTarget.style.color = "var(--text-muted)"}
          >
            <X size={18} />
          </button>
        </div>

        {/* Content grid */}
        <div style={{ flex: 1, display: "flex", overflow: "hidden" }}>
          {/* File List (Left) */}
          <div style={{
            width: 260, borderRight: "1px solid var(--border-panel)",
            background: "var(--bg-sidebar)", padding: 12,
            display: "flex", flexDirection: "column", gap: 6
          }}>
            <span style={{ fontSize: 10, fontWeight: 600, color: "var(--text-disabled)", letterSpacing: "0.5px", paddingLeft: 6, marginBottom: 4 }}>
              PROJECT STRUCTURE
            </span>

            <div style={{ display: "flex", alignItems: "center", gap: 6, padding: "6px 8px", fontSize: 12, color: "var(--text-primary)" }}>
              <Folder size={14} style={{ color: "var(--accent-yellow)" }} />
              <span>{projectId}</span>
            </div>

            <div style={{ display: "flex", flexDirection: "column", gap: 2, paddingLeft: 10 }}>
              {files.map(f => {
                const isSelected = selectedFile === f.id;
                return (
                  <button
                    key={f.id}
                    onClick={() => setSelectedFile(f.id)}
                    style={{
                      display: "flex", alignItems: "center", gap: 8,
                      padding: "6px 10px", borderRadius: 6, border: "none",
                      textAlign: "left", cursor: "pointer", fontSize: 11,
                      background: isSelected ? "rgba(122, 162, 247, 0.15)" : "transparent",
                      color: isSelected ? "var(--text-bright)" : "var(--text-primary)",
                      fontWeight: isSelected ? 500 : 400,
                      transition: "all 0.15s"
                    }}
                  >
                    {f.type === "code" ? (
                      <FileCode size={13} style={{ color: "var(--accent-blue)" }} />
                    ) : (
                      <FileText size={13} style={{ color: "var(--text-disabled)" }} />
                    )}
                    <span style={{ overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }}>
                      {f.name}
                    </span>
                  </button>
                );
              })}
            </div>
          </div>

          {/* Preview Container (Right) */}
          <div style={{ flex: 1, display: "flex", flexDirection: "column", background: "var(--bg-editor)" }}>
            <div style={{
              padding: "8px 16px", background: "rgba(0,0,0,0.15)",
              borderBottom: "1px solid var(--border-panel)",
              display: "flex", alignItems: "center", justifyItems: "center", gap: 8
            }}>
              <span style={{ fontSize: 11, color: "var(--text-muted)" }}>Previewing</span>
              <code style={{ fontSize: 11, color: "var(--accent-blue)", background: "rgba(122,162,247,0.08)", padding: "2px 6px", borderRadius: 4 }}>
                {currentFile.name}
              </code>
            </div>

            <div style={{ flex: 1, overflow: "auto", padding: 16 }}>
              <pre style={{
                margin: 0,
                fontFamily: "var(--font-mono)",
                fontSize: 12,
                color: "var(--text-primary)",
                lineHeight: 1.5,
                whiteSpace: "pre-wrap"
              }}>
                <code>{currentFile.content}</code>
              </pre>
            </div>
          </div>
        </div>

        {/* Error banner if any */}
        {error && (
          <div style={{
            background: "rgba(247, 118, 142, 0.15)",
            color: "var(--accent-red)",
            padding: "8px 16px",
            fontSize: 11,
            borderTop: "1px solid var(--border-panel)",
            display: "flex", alignItems: "center", gap: 8
          }}>
            <Info size={14} />
            <span>{error}</span>
          </div>
        )}

        {/* Footer */}
        <div style={{
          padding: "16px 20px", borderTop: "1px solid var(--border-panel)",
          background: "var(--bg-sidebar)",
          display: "flex", alignItems: "center", justifyContent: "space-between"
        }}>
          <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
            <Settings size={14} style={{ color: "var(--text-disabled)" }} />
            <span style={{ fontSize: 11, color: "var(--text-muted)" }}>Target directory:</span>
            <code style={{ fontSize: 11, color: "var(--text-bright)", background: "rgba(255,255,255,0.05)", padding: "4px 8px", borderRadius: 4 }}>
              ~/CodeSentinel-projects/{projectId}/
            </code>
          </div>

          <div style={{ display: "flex", alignItems: "center", gap: 10 }}>
            <button
              onClick={onClose}
              disabled={writing}
              style={{
                padding: "8px 16px", borderRadius: 6, fontSize: 12, fontWeight: 500,
                background: "transparent", border: "1px solid var(--border-panel)",
                color: "var(--text-primary)", cursor: "pointer", transition: "all 0.15s"
              }}
              onMouseOver={e => e.currentTarget.style.background = "rgba(255,255,255,0.05)"}
              onMouseOut={e => e.currentTarget.style.background = "transparent"}
            >
              Cancel
            </button>

            <button
              onClick={handleWrite}
              disabled={writing}
              style={{
                padding: "8px 20px", borderRadius: 6, fontSize: 12, fontWeight: 500,
                background: "var(--accent-blue)", border: "none",
                color: "#ffffff", cursor: "pointer", display: "flex", alignItems: "center", gap: 8,
                transition: "all 0.15s", opacity: writing ? 0.7 : 1
              }}
              onMouseOver={e => e.currentTarget.style.filter = "brightness(1.15)"}
              onMouseOut={e => e.currentTarget.style.filter = "none"}
            >
              {writing ? (
                <>
                  <Loader2 size={14} style={{ animation: "spin 1s linear infinite" }} />
                  Writing...
                </>
              ) : (
                <>
                  <Check size={14} />
                  Accept & Write
                </>
              )}
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
